baseurl = "/"
languageCode = "en-us"
title = "T-Mobile Open Source"
theme = "tmo-oss-theme"
googleAnalytics = "UA-20393691-7"
disqusShortname= "tmo-oss-internal"

[params]
org_name = "tmobile"
name = "T-Mobile"
description = "Open source at the Un-carrier."
favicon = "favicon.ico"
  [params.footer]
  copyright = "Copyright 2020. All Rights Reserved."

  [params.hero]
  headline1 = "AT THE"
  headline2 = "OPEN SOURCE"
  headline3 = "UN-CARRIER"
  slogan = "Transforming wireless through technology innovation."

  [params.hero.cta]
  text = "VIEW PROJECTS"
  navigate_to = "#PROJECTS"

  [params.projects]
  headline = "PROJECTS"
  description = "All of our projects are available at <a href='https://github.com/tmobile' target='_github-tmobile'>github.com/tmobile</a>"

  [params.code]
  headline = "CODE OF CONDUCT"
  summary = "In the interest of fostering an open and welcoming environment, we as contributors and maintainers pledge to make participation in our community a harassment-free experience for everyone, regardless of age, body size, disability, ethnicity, gender identity and expression, level of experience, nationality, personal appearance, race, religion, or sexual identity and orientation."
    [params.code.cta]
    text = "VIEW DETAILS"
    navigate_to = "/conduct.html"

  [params.license]
  headline = "CONTRIBUTOR LICENSE AGREEMENT"
  summary = "All T-Mobile open source projects are licensed under the Apache License 2.0. It is a permissive free software license written by the Apache Software Foundation. It requires preservation of the copyright notice and disclaimer. Like other free software licenses, it allows the user the freedom to use the software for any purpose, to distribute it, to modify it, and to distribute modified versions without concern for royalties."
    [params.license.cta]
    text = "VIEW LICENSE"
    navigate_to = "https://www.apache.org/licenses/LICENSE-2.0"

  [params.careers]
  headline = "INTERESTED IN A CAREER WITH T-MOBILE?"
  summary = "At T-Mobile, we're breaking the rules of wireless and we're just getting started. Join our revolution and change wireless for good."
    [params.careers.cta]
    text = "VIEW CAREERS"
    navigate_to = "https://tmobile.careers"

  [params.blog]
  headline = "BLOG"
  summary = "Read about T-Mobile technology development, release details and other insights from app teams."
  navigate_to = "/blog/posts"

  [params.authors]
    [params.authors.nick]
    name = "Nicholas Criss"
    [params.authors.ram]
    name = "Ram Gopinathan"
    [params.authors.satish]
    name = "Satish Malireddi"
    [params.authors.prashant]
    name = "Prashant Gupta"

  [params.events]
  headline = "EVENTS CALENDAR"
  summary = "Keep up to date on new releases and upcoming events."

  [params.videos]
  headline = "VIDEOS"
  summary = "Check out T-Mobile conference and meetup presentations, demos and hackathons."
